import { NewsItem } from '@/types/news';

export const NEWS_DUMMY: NewsItem[] = [
  {
    id: '1',
    source: '로이터',
    time: '오전 10:30',
    isLive: true,
    title: '삼성전자, 북미 최대 데이터센터와 NVMe SSD 공급 계약 체결',
    summary: [
      '북미 대형 데이터센터와 대규모 SSD 공급 확정',
      '고부가가치 제품군 확대로 수익성 개선 기대',
      '향후 2년간 안정적인 매출처 확보',
    ],
    categories: ['기업 이벤트'],
    companies: ['삼성전자'],
  },
  {
    id: '2',
    source: '한국경제',
    time: '오전 9:15',
    isLive: false,
    title: '현대차, 자율주행 소프트웨어 업데이트 발표… 레벨 3 상용화 본격화',
    summary: ['레벨 3 자율주행 국내 첫 상용화 선언', '2026년 하반기 양산 모델 적용 예정'],
    categories: ['산업섹터'],
    companies: ['현대차'],
  },
  {
    id: '3',
    source: '연합뉴스',
    time: '오전 8:50',
    isLive: false,
    title: 'SK하이닉스, HBM4 양산 일정 앞당겨… 엔비디아 납품 확대 기대',
    summary: [],
    categories: ['기업실적'],
    companies: ['SK하이닉스'],
  },
  {
    id: '4',
    source: 'Bloomberg',
    time: '오전 8:10',
    isLive: false,
    title: 'NVIDIA, Blackwell GPU 수요 급증에 1분기 생산 전량 상반기 출하',
    summary: ['데이터센터 고객사 선주문 물량 전분기 대비 140% 증가', '1분기 생산분 이미 완판… 공급 부족 지속 전망'],
    categories: ['기업실적'],
    companies: ['엔비디아'],
  },
  {
    id: '5',
    source: 'Reuters',
    time: '오전 7:55',
    isLive: false,
    title: 'Apple, 인도 생산 비율 25%로 확대 계획 공식화',
    summary: [],
    categories: ['기업 이벤트'],
    companies: ['애플'],
  },
  {
    id: '6',
    source: 'Financial Times',
    time: '오전 7:30',
    isLive: false,
    title: '유럽 탄소 국경세, 국제 제조업체 수출 영향 우려',
    summary: ['탄소 국경 조정 메커니즘(CBAM) 2026년 본격 시행', '철강·알루미늄·시멘트 수출 기업 직접 영향권'],
    categories: ['정책/규제'],
    companies: [],
  },
  {
    id: '7',
    source: 'Nikkei',
    time: '오전 7:10',
    isLive: false,
    title: '토요타, 전고체 배터리 사업 분사… 별도 법인 설립 완료',
    summary: [],
    categories: ['기업 이벤트'],
    companies: ['토요타'],
  },
  {
    id: '8',
    source: '매일경제',
    time: '오전 6:50',
    isLive: false,
    title: '원·달러 환율 1,380원대 돌파… 수출기업 환차익 기대',
    summary: ['미 연준 금리 동결 장기화 전망에 달러 강세', '수출 대형주 중심 외국인 순매수 유입'],
    categories: ['금융시장', '거시경제'],
    companies: [],
  },
  {
    id: '9',
    source: '조선비즈',
    time: '오전 6:20',
    isLive: false,
    title: 'LG에너지솔루션, 미국 ITC에 중국 배터리 업체 특허 침해 제소',
    summary: ['CATL·BYD 대상 337조 위반 제소', '국내 배터리 3사 특허 분쟁 전선 확대'],
    categories: ['정책/규제'],
    companies: ['LG에너지솔루션'],
  },
  {
    id: '10',
    source: 'WSJ',
    time: '오전 5:45',
    isLive: false,
    title: '소프트뱅크, ARM 지분 추가 매각 검토… 비전펀드 유동성 확보',
    summary: [],
    categories: ['금융시장'],
    companies: ['소프트뱅크', 'ARM'],
  },
  {
    id: '11',
    source: 'AP',
    time: '오전 5:20',
    isLive: false,
    title: '중동 긴장 고조에 국제유가 배럴당 90달러 돌파',
    summary: ['이란·이스라엘 갈등 재점화로 호르무즈 해협 리스크 부각', 'WTI·브렌트유 동반 급등'],
    categories: ['지정학', '원자재'],
    companies: [],
  },
  {
    id: '12',
    source: '한국경제',
    time: '오전 4:55',
    isLive: false,
    title: '구리 가격 3개월 만에 최고치… 중국 인프라 투자 확대 기대감',
    summary: [],
    categories: ['원자재', '거시경제'],
    companies: [],
  },
];
